"""

Here are the api calls defined. Each entry should have 'library' and 'name' fields.

"""
cublas = []
cusolver = []

cublas.append({"library": "cublas",
               "name": "dger",
               "args": [{"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "double",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrX",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "incx",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrY",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "incy",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "zgeru",
               "args": [{"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "cuDoubleComplex",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrX",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "incx",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrY",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "incy",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "sgemm",
               "args": [{"name": "transa",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "transb",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "K",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "float",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "float",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrB",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "float",
                         "const": True,
                        },
                        {"name": "ldb",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "beta",
                         "type": "float",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrC",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "float",
                         "const": True,
                        },
                        {"name": "ldc",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "dgemm",
               "args": [{"name": "transa",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "transb",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "K",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "double",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrB",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "ldb",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "beta",
                         "type": "double",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrC",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "ldc",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "zgemm",
               "args": [{"name": "transa",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "transb",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "K",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "cuDoubleComplex",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrB",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "ldb",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "beta",
                         "type": "cuDoubleComplex",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrC",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "ldc",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "sgemv",
               "args": [{"name": "trans",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "float",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "float",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrX",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "float",
                         "const": True,
                        },
                        {"name": "incx",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "beta",
                         "type": "float",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrY",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "float",
                         "const": True,
                        },
                        {"name": "incy",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "dgemv",
               "args": [{"name": "trans",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "double",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrX",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "incx",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "beta",
                         "type": "double",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrY",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "incy",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "zgemv",
               "args": [{"name": "trans",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "cuDoubleComplex",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrX",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "incx",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "beta",
                         "type": "cuDoubleComplex",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrY",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "incy",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "dtrsm",
               "args": [{"name": "side",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "uplo",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "transa",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "diag",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "double",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrB",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "double",
                         "const": True,
                        },
                        {"name": "ldb",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

cublas.append({"library": "cublas",
               "name": "ztrsm",
               "args": [{"name": "side",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "uplo",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "transa",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "diag",
                         "type": "char",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "M",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "N",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "alpha",
                         "type": "cuDoubleComplex",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrA",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "lda",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                        {"name": "devPtrB",
                         "type": "devptr_t",
                         "offload": True,
                         "recast_offload": "cuDoubleComplex",
                         "const": True,
                        },
                        {"name": "ldb",
                         "type": "int",
                         "offload": False,
                         "const": True,
                        },
                     ]})

"""

###################################################################

  cusolver part starts here

###################################################################

"""

cusolver.append({"library": "cusolver",
                 "name": "dgetrf_buffersize",
                 "new_name": "cusolverDnDgetrf_bufferSize",
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "N",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "norefpass": True,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "zgetrf_buffersize",
                 "new_name": "cusolverDnZgetrf_bufferSize",
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "N",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "norefpass": True,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "dpotrf_buffersize",
                 "new_name": "cusolverDnDpotrf_bufferSize",
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" }]],
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "norefpass": True,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "zpotrf_buffersize",
                 "new_name": "cusolverDnZpotrf_bufferSize",
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" }]],
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "norefpass": True,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "dpotri_buffersize",
                 "new_name": "cusolverDnDpotri_bufferSize",
                 "versions": [  [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" }],
                                [{"variable": "fillm",
                                  "value": "L",
                                  "pass": "CUBLAS_FILL_MODE_LOWER" }]],
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "norefpass": True,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "zpotri_buffersize",
                 "new_name": "cusolverDnZpotri_bufferSize",
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" }]],
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "norefpass": True,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "dsyevd_buffersize",
                 "new_name": "cusolverDnDsyevd_bufferSize",
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" },
                                {"variable": "jobmode",
                                 "value": "N",
                                 "pass": "CUSOLVER_EIG_MODE_NOVECTOR" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" },
                                {"variable": "jobmode",
                                 "value": "N",
                                 "pass": "CUSOLVER_EIG_MODE_NOVECTOR" }],
                               [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" },
                                {"variable": "jobmode",
                                 "value": "V",
                                 "pass": "CUSOLVER_EIG_MODE_VECTOR" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" },
                                {"variable": "jobmode",
                                 "value": "V",
                                 "pass": "CUSOLVER_EIG_MODE_VECTOR" }] ],
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "jobmode",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "W",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lwork",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "norefpass": True,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "dgetrf",
                 "new_name": "cusolverDnDgetrf",
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "N",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "devIpiv",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "zgetrf",
                 "new_name": "cusolverDnZgetrf",
                 "suffix": False,
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "N",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "cuDoubleComplex",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "cuDoubleComplex",
                           "const": False,
                          },
                          {"name": "devIpiv",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "dgetrs",
                 "new_name": "cusolverDnDgetrs",
                 "suffix": False,
                 "versions": [ [{"variable": "trans",
                                 "value": "N",
                                 "pass": "CUBLAS_OP_N" }],
                               [{"variable": "trans",
                                 "value": "L",
                                 "pass": "CUBLAS_OP_T" }] ],
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "trans",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "nrhs",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "devIpiv",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                          {"name": "B",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "ldb",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "zgetrs",
                 "new_name": "cusolverDnZgetrs",
                 "suffix": False,
                 "versions": [ [{"variable": "trans",
                                 "value": "N",
                                 "pass": "CUBLAS_OP_N" }],
                               [{"variable": "trans",
                                 "value": "L",
                                 "pass": "CUBLAS_OP_T" }],
                               [{"variable": "trans",
                                 "value": "C",
                                 "pass": "CUBLAS_OP_C" }] ],
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "trans",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "nrhs",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "cuDoubleComplex",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "devIpiv",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                          {"name": "B",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "cuDoubleComplex",
                           "const": False,
                          },
                          {"name": "ldb",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "dpotrs",
                 "new_name": "cusolverDnDpotrs",
                 "suffix": False,
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" }] ],
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "nrhs",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "B",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "ldb",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "zpotrs",
                 "new_name": "cusolverDnZpotrs",
                 "suffix": False,
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" }] ],
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "nrhs",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "cuDoubleComplex",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "B",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "cuDoubleComplex",
                           "const": False,
                          },
                          {"name": "ldb",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "dpotri",
                 "new_name": "cusolverDnDpotri",
                 "suffix": False,
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" }] ],
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "lwork",
                           "type": "int",
                           "offload": False,
                           "recast_offload": "int",
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "zpotri",
                 "new_name": "cusolverDnZpotri",
                 "suffix": False,
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" }] ],
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "cuDoubleComplex",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "cuDoubleComplex",
                           "const": False,
                          },
                          {"name": "lwork",
                           "type": "int",
                           "offload": False,
                           "recast_offload": "int",
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})

cusolver.append({"library": "cusolver",
                 "name": "dsyevd",
                 "new_name": "cusolverDnDsyevd",
                 "suffix": False,
                 "versions": [ [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" },
                                {"variable": "jobmode",
                                 "value": "N",
                                 "pass": "CUSOLVER_EIG_MODE_NOVECTOR" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" },
                                {"variable": "jobmode",
                                 "value": "N",
                                 "pass": "CUSOLVER_EIG_MODE_NOVECTOR" }],
                               [{"variable": "fillm",
                                 "value": "U",
                                 "pass": "CUBLAS_FILL_MODE_UPPER" },
                                {"variable": "jobmode",
                                 "value": "V",
                                 "pass": "CUSOLVER_EIG_MODE_VECTOR" }],
                               [{"variable": "fillm",
                                 "value": "L",
                                 "pass": "CUBLAS_FILL_MODE_LOWER" },
                                {"variable": "jobmode",
                                 "value": "V",
                                 "pass": "CUSOLVER_EIG_MODE_VECTOR" }] ],
                 "args": [{"name": "handle",
                           "type": "long int",
                           "offload": False,
                           "const": True,
                           "recast": {"to": "cusolverDnHandle_t"},
                          },
                          {"name": "status",
                           "type": "int",
                           "offload": False,
                           "const": False,
                           "return": True,
                          },
                          {"name": "jobmode",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "fillm",
                           "type": "char",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "M",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "A",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "void",
                           "const": False,
                          },
                          {"name": "lda",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "W",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "workspace",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "double",
                           "const": False,
                          },
                          {"name": "lwork",
                           "type": "int",
                           "offload": False,
                           "const": False,
                          },
                          {"name": "devInfo",
                           "type": "void",
                           "offload": True,
                           "recast_offload": "int",
                           "const": False,
                          },
                       ]})
