!TL off
!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.3 (r3163) - 09/25/2009 09:03
!
!  Differentiation of jastrowgrad in reverse (adjoint) mode:
!   gradient, with respect to input variables: grad2 rc vj gradv
!   of linear combination of output variables: grad2 rc vj gradv
SUBROUTINE JASTROWGRAD_B(rc, rcb, vj, vjb, iesd, jastrow, gradv, gradvb&
        &, grad2, grad2b, ispin)
    IMPLICIT NONE
    REAL*8 :: r, rc(3), jastrow, vj(*), grad, grad2, aux, aux2, aux3, &
            &  peffm, gradv(3), cost, acost, bcost, rz, dxrz, dxr, fat, rs, fat0
    REAL*8 :: rb, rcb(3), vjb(*), gradb, grad2b, auxb, aux2b, aux3b, &
            &  gradvb(3), costb, acostb, bcostb, rzb, dxrzb, dxrb, fatb, rsb, fat0b
    INTEGER :: iesd, ispin, j
    INTEGER :: branch
    real*8 dxrz_old, dxr_old, aux_old, aux2_old
    DOUBLE PRECISION :: x3b
    REAL*8 :: temp3
    REAL*8 :: temp29
    REAL*8 :: temp25b2
    REAL*8 :: temp2
    REAL*8 :: temp28
    REAL*8 :: temp25b1
    REAL*8 :: temp1
    REAL*8 :: temp27
    REAL*8 :: temp25b0
    REAL*8 :: temp0
    REAL*8 :: temp13b
    REAL*8 :: temp26
    REAL*8 :: temp21b
    REAL*8 :: temp25
    DOUBLE PRECISION :: x10b
    REAL*8 :: temp24
    INTRINSIC DEXP
    REAL*8 :: temp23
    REAL*8 :: temp9b1
    REAL*8 :: temp22
    DOUBLE PRECISION :: x6b
    REAL*8 :: temp9b0
    REAL*8 :: temp21
    REAL*8 :: temp20
    REAL*8 :: temp30b7
    REAL*8 :: temp35b2
    DOUBLE PRECISION :: x12
    REAL*8 :: temp30b6
    REAL*8 :: temp35b1
    DOUBLE PRECISION :: x11
    REAL*8 :: temp30b5
    REAL*8 :: temp35b0
    DOUBLE PRECISION :: x10
    REAL*8 :: temp30b4
    REAL*8 :: temp32b
    REAL*8 :: temp30b3
    REAL*8 :: temp40b
    REAL*8 :: tempb7
    REAL*8 :: temp30b2
    DOUBLE PRECISION :: x9b
    REAL*8 :: tempb6
    DOUBLE PRECISION :: temp30b1
    REAL*8 :: tempb5
    REAL*8 :: temp30b0
    REAL*8 :: tempb4
    REAL*8 :: temp19b
    DOUBLE PRECISION :: tempb3
    REAL*8 :: tempb2
    REAL*8 :: temp35b
    REAL*8 :: tempb1
    REAL*8 :: temp43b
    REAL*8 :: tempb0
    REAL*8 :: temp0b
    DOUBLE PRECISION :: x9
    INTRINSIC MAX
    DOUBLE PRECISION :: x8
    DOUBLE PRECISION :: x7
    REAL*8 :: temp33b9
    DOUBLE PRECISION :: x6
    REAL*8 :: temp33b8
    DOUBLE PRECISION :: x5
    REAL*8 :: temp33b7
    REAL*8 :: temp38b
    DOUBLE PRECISION :: x4
    REAL*8 :: temp33b6
    DOUBLE PRECISION :: x3
    REAL*8 :: temp3b
    DOUBLE PRECISION :: temp33b5
    DOUBLE PRECISION :: x2
    REAL*8 :: temp33b4
    DOUBLE PRECISION :: x1
    REAL*8 :: temp33b3
    DOUBLE PRECISION :: x2b
    REAL*8 :: temp19
    REAL*8 :: temp33b2
    REAL*8 :: temp18
    DOUBLE PRECISION :: temp33b1
    REAL*8 :: temp17
    REAL*8 :: temp33b0
    REAL*8 :: temp16
    REAL*8 :: temp12b
    REAL*8 :: temp6b
    REAL*8 :: temp15
    REAL*8 :: temp20b
    REAL*8 :: temp14
    REAL*8 :: temp13
    REAL*8 :: temp12
    DOUBLE PRECISION :: x5b
    REAL*8 :: temp11
    REAL*8 :: temp10
    REAL*8 :: temp26b1
    REAL*8 :: temp43b2
    REAL*8 :: temp15b
    REAL*8 :: temp26b0
    REAL*8 :: temp43b1
    DOUBLE PRECISION :: temp9b
    DOUBLE PRECISION :: x12b
    DOUBLE PRECISION :: temp43b0
    REAL*8 :: temp31b
    REAL*8 :: temp44
    REAL*8 :: temp43
    DOUBLE PRECISION :: x8b
    REAL*8 :: temp42
    REAL*8 :: temp41
    REAL*8 :: temp31b8
    REAL*8 :: temp40
    REAL*8 :: temp18b
    REAL*8 :: temp31b7
    REAL*8 :: temp26b
    REAL*8 :: temp31b6
    REAL*8 :: temp31b5
    DOUBLE PRECISION :: temp34b
    REAL*8 :: temp31b4
    REAL*8 :: temp42b
    REAL*8 :: temp31b3
    DOUBLE PRECISION :: tempb
    REAL*8 :: temp31b2
    DOUBLE PRECISION :: temp31b1
    REAL*8 :: temp31b0
    REAL*8 :: temp0b0
    REAL*8 :: temp37b
    REAL*8 :: temp45b
    REAL*8 :: temp2b
    DOUBLE PRECISION :: x1b
    REAL*8 :: temp41b0
    REAL*8 :: temp11b
    REAL*8 :: temp5b
    REAL*8 :: temp39b1
    INTRINSIC LOG
    REAL*8 :: temp39b0
    DOUBLE PRECISION :: x4b
    REAL*8 :: temp39
    REAL*8 :: temp34b2
    REAL*8 :: temp38
    REAL*8 :: temp34b1
    REAL*8 :: temp37
    REAL*8 :: temp14b
    REAL*8 :: temp34b0
    REAL*8 :: temp36
    REAL*8 :: temp22b
    DOUBLE PRECISION :: x11b
    REAL*8 :: temp35
    DOUBLE PRECISION :: temp30b
    REAL*8 :: temp34
    REAL*8 :: temp33
    DOUBLE PRECISION :: x7b
    DOUBLE PRECISION :: temp32
    DOUBLE PRECISION :: temp31
    DOUBLE PRECISION :: temp30
    DOUBLE PRECISION :: temp25b
    REAL*8 :: temp44b1
    REAL*8 :: temp33b
    REAL*8 :: temp44b0
    REAL*8 :: temp41b
    REAL*8 :: temp36b
    REAL*8 :: temp37b0
    REAL*8 :: temp44b
    DOUBLE PRECISION :: temp1b
    INTRINSIC DSQRT
    REAL*8 :: temp
    REAL*8 :: temp32b1
    REAL*8 :: temp9
    REAL*8 :: temp32b0
    REAL*8 :: temp8
    REAL*8 :: temp1b1
    REAL*8 :: temp39b
    REAL*8 :: temp7
    REAL*8 :: temp1b0
    REAL*8 :: temp10b
    REAL*8 :: temp6
    REAL*8 :: temp4b
    REAL*8 :: temp5
    REAL*8 :: temp4
    !        Output jastrow= log (two body Jastrow)
    !        grad2= 2/r u'  + u''
    !        grad= u'
    !        gradv= grad u
    !     input r output jastrow grad e grad2
    SELECT CASE  (iesd)
    CASE (4)
        x1 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x1 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x1
            !     CALL PUSHINTEGER4(0)
        END IF
        fat = DEXP(-(vj(1) * r))
        IF (ispin .LT. 0) THEN
            !        jastrow=dexp(jastrow)
            grad = 0.5d0 * fat
            grad2 = 0.5d0 * fat * (2.d0 - vj(1) * r)
            !     CALL PUSHINTEGER4(1)
        ELSE
            !        jastrow=dexp(jastrow)
            grad = 0.25d0 * fat
            grad2 = 0.25d0 * fat * (2.d0 - vj(1) * r)
            !     CALL PUSHINTEGER4(0)
        END IF
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        gradb = costb / r
        rb = -(grad2 * grad2b / r**2) - grad * costb / r**2
        grad2b = grad2b / r
        !   CALL POPINTEGER4(branch)
        !   IF (branch .LT. 1) THEN
        IF (ispin .ge. 0) THEN
            tempb1 = 0.25d0 * fat * grad2b
            fatb = 0.25d0 * gradb + 0.25d0 * (2.d0 - vj(1) * r) * grad2b
            vjb(1) = vjb(1) - r * tempb1
            rb = rb - vj(1) * tempb1
        ELSE
            tempb2 = 0.5d0 * fat * grad2b
            fatb = 0.5d0 * gradb + 0.5d0 * (2.d0 - vj(1) * r) * grad2b
            vjb(1) = vjb(1) - r * tempb2
            rb = rb - vj(1) * tempb2
        END IF
        !   tempb0 = DEXP(-(vj(1)*r))*fatb
        tempb0 = fat * fatb
        vjb(1) = vjb(1) - r * tempb0
        rb = rb - vj(1) * tempb0
        !   CALL POPINTEGER4(branch)
        IF (x1 .ge. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x1b = rb
        ELSE
            x1b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            tempb = 0.0
        ELSE
            tempb = x1b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * tempb
        rcb(2) = rcb(2) + 2 * rc(2) * tempb
        rcb(3) = rcb(3) + 2 * rc(3) * tempb
    CASE (-4)
        x2 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x2 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x2
            !     CALL PUSHINTEGER4(0)
        END IF
        fat = DEXP(-(vj(1) * r))
        !        jastrow=dexp(jastrow)
        grad = 0.5d0 * fat
        grad2 = 0.5d0 * fat * (2.d0 - vj(1) * r)
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        gradb = costb / r
        rb = -(grad2 * grad2b / r**2) - grad * costb / r**2
        grad2b = grad2b / r
        tempb4 = 0.5d0 * fat * grad2b
        fatb = 0.5d0 * gradb + 0.5d0 * (2.d0 - vj(1) * r) * grad2b
        !   tempb5 = DEXP(-(vj(1)*r))*fatb
        tempb5 = fat * fatb
        vjb(1) = vjb(1) - r * tempb5 - r * tempb4
        rb = rb - vj(1) * tempb5 - vj(1) * tempb4
        !   CALL POPINTEGER4(branch)
        IF (x2 .GE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x2b = rb
        ELSE
            x2b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            tempb3 = 0.0
        ELSE
            tempb3 = x2b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * tempb3
        rcb(2) = rcb(2) + 2 * rc(2) * tempb3
        rcb(3) = rcb(3) + 2 * rc(3) * tempb3
    CASE (8)
        ! jastrow for pseudo soft
        r = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        fat = DEXP(-(vj(1) * r**3))
        cost = fat * 3 * r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        temp0 = r**3
        temp0b = -(3 * (3 * (vj(1) * temp0) - 4) * grad2b)
        temp0b0 = -(3**2 * r * fat * grad2b)
        fatb = 3 * r * costb + r * temp0b
        temp = r**3
        tempb6 = DEXP(-(vj(1) * temp)) * fatb
        rb = 3 * fat * costb - vj(1) * 3 * r**2 * tempb6 + vj(1) * 3 * r**2 * temp0b0 + fat * &
                &      temp0b
        vjb(1) = vjb(1) + temp0 * temp0b0 - temp * tempb6
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            tempb7 = 0.0
        ELSE
            tempb7 = rb / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * tempb7
        rcb(2) = rcb(2) + 2 * rc(2) * tempb7
        rcb(3) = rcb(3) + 2 * rc(3) * tempb7
    CASE (9)
        x3 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x3 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x3
            !     CALL PUSHINTEGER4(0)
        END IF
        acost = vj(2) * (1 + vj(1)) / (4.d0 * vj(1))
        fat0 = (1.d0 - r / vj(2))**2
        fat = 1.d0 + vj(1) * fat0
        grad = 2.d0 * acost * vj(1) * (1.d0 - r / vj(2)) / (vj(2) * fat)
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        costb = costb + 2 * grad2b
        gradb = costb / r
        temp8 = fat**2
        temp5 = vj(1) * fat0 / temp8
        temp7 = vj(2)**2
        temp6 = acost * vj(1) / temp7
        temp5b = temp6 * 4.d0 * grad2b / temp8
        temp2 = vj(2) * fat
        temp3 = acost * vj(1) / temp2
        temp4 = r / vj(2)
        temp3b = 2.d0 * (1.d0 - temp4) * gradb / temp2
        temp2b = -(temp3 * temp3b)
        fatb = vj(2) * temp2b - temp5 * 2 * fat * temp5b + temp6 * 2.d0 * grad2b / fat**2
        fat0b = vj(1) * fatb + vj(1) * temp5b
        temp4b = -(2.d0 * temp3 * gradb / vj(2))
        temp1 = r / vj(2)
        temp1b0 = -(2 * (1.d0 - temp1) * fat0b / vj(2))
        rb = temp4b + temp1b0 - grad * costb / r**2
        temp6b = -((2.d0 / fat - 4.d0 * temp5) * grad2b / temp7)
        acostb = vj(1) * temp3b + vj(1) * temp6b
        vjb(1) = vjb(1) + fat0 * temp5b + acost * temp6b
        vjb(2) = vjb(2) + fat * temp2b - temp4 * temp4b - temp6 * 2 * vj(2) * temp6b
        vjb(1) = vjb(1) + fat0 * fatb + acost * temp3b
        temp1b1 = acostb / (4.d0 * vj(1))
        vjb(2) = vjb(2) + (vj(1) + 1) * temp1b1 - temp1 * temp1b0
        vjb(1) = vjb(1) + (vj(2) - vj(2) * (vj(1) + 1) / vj(1)) * temp1b1
        !   CALL POPINTEGER4(branch)
        IF (x3 .GE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x3b = rb
        ELSE
            x3b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp1b = 0.0
        ELSE
            temp1b = x3b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp1b
        rcb(2) = rcb(2) + 2 * rc(2) * temp1b
        rcb(3) = rcb(3) + 2 * rc(3) * temp1b
    CASE (10)
        x4 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x4 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x4
            !     CALL PUSHINTEGER4(0)
        END IF
        acost = vj(2) * (1 + vj(1)) / (4.d0 * vj(1))
        IF (ispin .GT. 0) THEN
            fat0 = (1.d0 - 0.5d0 * r / vj(2))**2
            !     CALL PUSHINTEGER4(1)
        ELSE
            fat0 = (1.d0 - r / vj(2))**2
            !     CALL PUSHINTEGER4(0)
        END IF
        fat = 1.d0 + vj(1) * fat0
        IF (ispin .GT. 0) THEN
            grad = acost * vj(1) * (1.d0 - 0.5d0 * r / vj(2)) / (vj(2) * fat)
            !     CALL PUSHINTEGER4(0)
        ELSE
            grad = 2.d0 * acost * vj(1) * (1.d0 - r / vj(2)) / (vj(2) * fat)
            !     CALL PUSHINTEGER4(1)
        END IF
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        costb = costb + 2 * grad2b
        gradb = costb / r
        rb = -(grad * costb / r**2)
        !   CALL POPINTEGER4(branch)
        IF (ispin .GT. 0) THEN
            !   IF (branch .LT. 1) THEN
            temp17 = fat**2
            temp14 = vj(1) * fat0 / temp17
            temp16 = vj(2)**2
            temp15b = -((0.5d0 / fat - temp14) * grad2b / temp16)
            temp15 = acost * vj(1) / temp16
            temp14b = temp15 * grad2b / temp17
            temp11 = vj(2) * fat
            temp13 = r / vj(2)
            temp12b = (1.d0 - 0.5d0 * temp13) * gradb / temp11
            acostb = vj(1) * temp12b + vj(1) * temp15b
            vjb(1) = vjb(1) + fat0 * temp14b + acost * temp15b
            temp12 = acost * vj(1) / temp11
            temp13b = -(temp12 * 0.5d0 * gradb / vj(2))
            temp11b = -(temp12 * temp12b)
            vjb(2) = vjb(2) + fat * temp11b - temp13 * temp13b - temp15 * 2 * vj(2) * &
                    &        temp15b
            fatb = vj(2) * temp11b - temp14 * 2 * fat * temp14b + temp15 * 0.5d0 * grad2b / &
                    &        fat**2
            fat0b = vj(1) * temp14b
            rb = rb + temp13b
            vjb(1) = vjb(1) + acost * temp12b
        ELSE
            temp24 = fat**2
            temp21 = vj(1) * fat0 / temp24
            temp23 = vj(2)**2
            temp22b = -((2.d0 / fat - 4.d0 * temp21) * grad2b / temp23)
            temp22 = acost * vj(1) / temp23
            temp21b = temp22 * 4.d0 * grad2b / temp24
            temp18 = vj(2) * fat
            temp20 = r / vj(2)
            temp19b = 2.d0 * (1.d0 - temp20) * gradb / temp18
            acostb = vj(1) * temp19b + vj(1) * temp22b
            vjb(1) = vjb(1) + fat0 * temp21b + acost * temp22b
            temp19 = acost * vj(1) / temp18
            temp20b = -(2.d0 * temp19 * gradb / vj(2))
            temp18b = -(temp19 * temp19b)
            vjb(2) = vjb(2) + fat * temp18b - temp20 * temp20b - temp22 * 2 * vj(2) * &
                    &        temp22b
            fatb = vj(2) * temp18b - temp21 * 2 * fat * temp21b + temp22 * 2.d0 * grad2b / &
                    &        fat**2
            fat0b = vj(1) * temp21b
            rb = rb + temp20b
            vjb(1) = vjb(1) + acost * temp19b
        END IF
        vjb(1) = vjb(1) + fat0 * fatb
        fat0b = fat0b + vj(1) * fatb
        !   CALL POPINTEGER4(branch)
        IF (ispin .LE. 0) THEN
            !   IF (branch .LT. 1) THEN
            temp9 = r / vj(2)
            temp9b1 = -(2 * (1.d0 - temp9) * fat0b / vj(2))
            rb = rb + temp9b1
            vjb(2) = vjb(2) - temp9 * temp9b1
        ELSE
            temp10 = r / vj(2)
            temp10b = -(2 * (1.d0 - 0.5d0 * temp10) * 0.5d0 * fat0b / vj(2))
            rb = rb + temp10b
            vjb(2) = vjb(2) - temp10 * temp10b
        END IF
        temp9b0 = acostb / (4.d0 * vj(1))
        vjb(2) = vjb(2) + (vj(1) + 1) * temp9b0
        vjb(1) = vjb(1) + (vj(2) - vj(2) * (vj(1) + 1) / vj(1)) * temp9b0
        !   CALL POPINTEGER4(branch)
        IF (x4 .ge. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x4b = rb
        ELSE
            x4b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp9b = 0.0
        ELSE
            temp9b = x4b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp9b
        rcb(2) = rcb(2) + 2 * rc(2) * temp9b
        rcb(3) = rcb(3) + 2 * rc(3) * temp9b
    CASE (5)
        x5 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x5 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x5
            !     CALL PUSHINTEGER4(0)
        END IF
        aux = DEXP(-(vj(1) * r))
        aux2 = DEXP(-(vj(2) * r))
        aux3 = 0.5d0 / (vj(1) + vj(3) * vj(2))
        !        jastrow=dexp(jastrow)
        grad = aux3 * (vj(1) * aux + vj(3) * vj(2) * aux2)
        grad2 = aux3 * (2.d0 * vj(2) * vj(3) * aux2 - vj(2)**2 * vj(3) * aux2 * r - vj(1) * aux * &
                &      (-2.d0 + vj(1) * r))
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        gradb = costb / r
        rb = -(grad2 * grad2b / r**2) - grad * costb / r**2
        grad2b = grad2b / r
        temp29 = vj(1) * r - 2.d0
        temp28 = vj(1) * aux
        temp27 = aux2 * r
        temp26 = vj(2)**2 * vj(3)
        temp26b = aux3 * grad2b
        temp26b0 = 2.d0 * vj(3) * temp26b
        aux3b = (vj(1) * aux + vj(3) * aux2 * vj(2)) * gradb + (2.d0 * (vj(2) * aux2 * vj(3)&
                &) - temp26 * temp27 - temp28 * temp29) * grad2b
        vjb(2) = vjb(2) + aux2 * temp26b0 - temp27 * vj(3) * 2 * vj(2) * temp26b
        temp26b1 = aux3 * gradb
        aux2b = vj(2) * vj(3) * temp26b1 - temp26 * r * temp26b + vj(2) * temp26b0
        vjb(3) = vjb(3) + (2.d0 * vj(2) * aux2 - temp27 * vj(2)**2) * temp26b
        auxb = vj(1) * temp26b1 - temp29 * vj(1) * temp26b
        temp25b0 = DEXP(-(vj(2) * r)) * aux2b
        temp25b1 = DEXP(-(vj(1) * r)) * auxb
        rb = rb + (-(temp28 * vj(1)) - temp26 * aux2) * temp26b - vj(1) * temp25b1 - &
                &      vj(2) * temp25b0
        vjb(1) = vjb(1) + aux * temp26b1 + (-(temp28 * r) - temp29 * aux) * temp26b
        vjb(3) = vjb(3) + vj(2) * aux2 * temp26b1
        vjb(2) = vjb(2) + vj(3) * aux2 * temp26b1
        temp25 = vj(1) + vj(3) * vj(2)
        temp25b2 = -(0.5d0 * aux3b / temp25**2)
        vjb(1) = vjb(1) + temp25b2
        vjb(3) = vjb(3) + vj(2) * temp25b2
        vjb(2) = vjb(2) + vj(3) * temp25b2 - r * temp25b0
        vjb(1) = vjb(1) - r * temp25b1
        !   CALL POPINTEGER4(branch)
        IF (x5 .GE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x5b = rb
        ELSE
            x5b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp25b = 0.0
        ELSE
            temp25b = x5b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp25b
        rcb(2) = rcb(2) + 2 * rc(2) * temp25b
        rcb(3) = rcb(3) + 2 * rc(3) * temp25b
    CASE (1)
        x6 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x6 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x6
            !     CALL PUSHINTEGER4(0)
        END IF
        aux = 1.d0 / (1.d0 + vj(1) * r)
        aux2 = aux * aux
        aux3 = aux2 * aux
        !           jastrow=dexp(jastrow)
        grad = 0.5d0 * aux2
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        gradb = costb / r
        aux3b = grad2b / r
        aux2b = aux * aux3b + 0.5d0 * gradb
        auxb = 2 * aux * aux2b + aux2 * aux3b
        temp30b0 = -(auxb / (vj(1) * r + 1.d0)**2)
        rb = vj(1) * temp30b0 - aux3 * grad2b / r**2 - grad * costb / r**2
        vjb(1) = vjb(1) + r * temp30b0
        !   CALL POPINTEGER4(branch)
        IF (x6 .GE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x6b = rb
        ELSE
            x6b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp30b = 0.0
        ELSE
            temp30b = x6b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp30b
        rcb(2) = rcb(2) + 2 * rc(2) * temp30b
        rcb(3) = rcb(3) + 2 * rc(3) * temp30b
    CASE (6)
        x7 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x7 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x7
            !     CALL PUSHINTEGER4(0)
        END IF
        IF (vj(2) .GT. 1d-9) THEN
            rs = (1.d0 - DEXP(-(vj(2) * r))) / vj(2)
            !     CALL PUSHINTEGER4(1)
        ELSE
            rs = r
            !     CALL PUSHINTEGER4(0)
        END IF
        aux = 1.d0 / (1.d0 + vj(1) * rs)
        aux2 = aux * aux
        aux3 = aux2 * aux
        !           jastrow=dexp(jastrow)
        grad = 0.5d0 * aux2 * DEXP(-(vj(2) * r))
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        temp31b = 2.d0 * grad2b / r
        gradb = temp31b + costb / r
        temp31b0 = DEXP(-(vj(2) * r)) * grad2b
        temp30 = DEXP(-(vj(2) * r))
        temp30b4 = -(vj(1) * aux3 * DEXP(-(vj(2) * r)) * temp31b0)
        temp30b5 = (-(vj(1) * aux3 * temp30) - 0.5d0 * (vj(2) * aux2)) * DEXP(-(vj(2) * r)&
                &) * grad2b
        temp30b6 = 0.5d0 * aux2 * DEXP(-(vj(2) * r)) * gradb
        rb = -(grad * temp31b / r) - vj(2) * temp30b6 - vj(2) * temp30b5 - vj(2) * &
                &      temp30b4 - grad * costb / r**2
        vjb(1) = vjb(1) - temp30 * aux3 * temp31b0
        aux3b = -(temp30 * vj(1) * temp31b0)
        vjb(2) = vjb(2) - r * temp30b6 - r * temp30b5 - 0.5d0 * aux2 * temp31b0 - r * &
                &      temp30b4
        aux2b = 0.5d0 * DEXP(-(vj(2) * r)) * gradb + aux * aux3b - 0.5d0 * vj(2) * &
                &      temp31b0
        auxb = 2 * aux * aux2b + aux2 * aux3b
        temp30b7 = -(auxb / (vj(1) * rs + 1.d0)**2)
        vjb(1) = vjb(1) + rs * temp30b7
        rsb = vj(1) * temp30b7
        !   CALL POPINTEGER4(branch)
        !   IF (branch .LT. 1) THEN
        IF (vj(2) .LE. 1d-9) THEN
            rb = rb + rsb
        ELSE
            temp30b2 = rsb / vj(2)
            temp30b3 = -(DEXP(-(vj(2) * r)) * temp30b2)
            vjb(2) = vjb(2) - (1.d0 - DEXP(-(vj(2) * r))) * temp30b2 / vj(2) - r * &
                    &        temp30b3
            rb = rb - vj(2) * temp30b3
        END IF
        !   CALL POPINTEGER4(branch)
        !   IF (branch .LT. 1) THEN
        IF (x7 .GE. 1d-9) THEN
            x7b = rb
        ELSE
            x7b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp30b1 = 0.0
        ELSE
            temp30b1 = x7b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp30b1
        rcb(2) = rcb(2) + 2 * rc(2) * temp30b1
        rcb(3) = rcb(3) + 2 * rc(3) * temp30b1
    CASE (7)
        x8 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x8 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x8
            !     CALL PUSHINTEGER4(0)
        END IF
        IF (vj(2) .GT. 1d-9) THEN
            rs = (1.d0 - DEXP(-(vj(2) * r))) / vj(2)
            !     CALL PUSHINTEGER4(1)
        ELSE
            rs = r
            !     CALL PUSHINTEGER4(0)
        END IF
        aux = 1.d0 / (1.d0 + vj(1) * rs)
        aux2 = aux * aux
        aux3 = aux2 * aux
        ! parallel
        IF (ispin .GT. 0) THEN
            grad = 0.25d0 * aux2 * DEXP(-(vj(2) * r))
            ! antiparallel
            !     CALL PUSHINTEGER4(0)
        ELSE
            grad = 0.5d0 * aux2 * DEXP(-(vj(2) * r))
            !     CALL PUSHINTEGER4(1)
        END IF
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        temp33b0 = 2.d0 * grad2b / r
        gradb = temp33b0 + costb / r
        rb = -(grad * temp33b0 / r) - grad * costb / r**2
        !   CALL POPINTEGER4(branch)
        IF (ispin .GT. 0) THEN
            !   IF (branch .LT. 1) THEN
            temp31 = DEXP(-(vj(2) * r))
            temp31b5 = 0.5d0 * DEXP(-(vj(2) * r)) * grad2b
            temp31b6 = -(vj(1) * aux3 * DEXP(-(vj(2) * r)) * temp31b5)
            temp31b7 = 0.5d0 * (-(vj(1) * aux3 * temp31) - 0.5d0 * (vj(2) * aux2)) * DEXP(-(&
                    &        vj(2) * r)) * grad2b
            vjb(1) = vjb(1) - temp31 * aux3 * temp31b5
            aux3b = -(temp31 * vj(1) * temp31b5)
            temp31b8 = 0.25d0 * aux2 * DEXP(-(vj(2) * r)) * gradb
            vjb(2) = vjb(2) - r * temp31b8 - r * temp31b7 - 0.5d0 * aux2 * temp31b5 - &
                    &        r * temp31b6
            rb = rb - vj(2) * temp31b8 - vj(2) * temp31b7 - vj(2) * temp31b6
            aux2b = 0.25d0 * DEXP(-(vj(2) * r)) * gradb - 0.5d0 * vj(2) * temp31b5
        ELSE
            temp33b = DEXP(-(vj(2) * r)) * grad2b
            temp32 = DEXP(-(vj(2) * r))
            temp32b = -(vj(1) * aux3 * DEXP(-(vj(2) * r)) * temp33b)
            temp32b0 = (-(vj(1) * aux3 * temp32) - 0.5d0 * (vj(2) * aux2)) * DEXP(-(vj(2) * &
                    &        r)) * grad2b
            vjb(1) = vjb(1) - temp32 * aux3 * temp33b
            aux3b = -(temp32 * vj(1) * temp33b)
            temp32b1 = 0.5d0 * aux2 * DEXP(-(vj(2) * r)) * gradb
            vjb(2) = vjb(2) - r * temp32b1 - r * temp32b0 - 0.5d0 * aux2 * temp33b - r&
                    & * temp32b
            rb = rb - vj(2) * temp32b1 - vj(2) * temp32b0 - vj(2) * temp32b
            aux2b = 0.5d0 * DEXP(-(vj(2) * r)) * gradb - 0.5d0 * vj(2) * temp33b
        END IF
        aux2b = aux2b + aux * aux3b
        auxb = 2 * aux * aux2b + aux2 * aux3b
        temp31b4 = -(auxb / (vj(1) * rs + 1.d0)**2)
        vjb(1) = vjb(1) + rs * temp31b4
        rsb = vj(1) * temp31b4
        !   CALL POPINTEGER4(branch)
        IF (vj(2) .LE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            rb = rb + rsb
        ELSE
            temp31b2 = rsb / vj(2)
            temp31b3 = -(DEXP(-(vj(2) * r)) * temp31b2)
            vjb(2) = vjb(2) - (1.d0 - DEXP(-(vj(2) * r))) * temp31b2 / vj(2) - r * &
                    &        temp31b3
            rb = rb - vj(2) * temp31b3
        END IF
        !   CALL POPINTEGER4(branch)
        IF (x8 .GE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x8b = rb
        ELSE
            x8b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp31b1 = 0.0
        ELSE
            temp31b1 = x8b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp31b1
        rcb(2) = rcb(2) + 2 * rc(2) * temp31b1
        rcb(3) = rcb(3) + 2 * rc(3) * temp31b1
    CASE (2)
        x9 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x9 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x9
            !     CALL PUSHINTEGER4(0)
        END IF
        IF (ispin .GT. 0) THEN
            aux = 1.d0 / (1.d0 + vj(2) * r)
            aux2 = aux * aux
            aux3 = aux2 * aux
            grad = 0.25d0 * aux2
            cost = grad / r
            costb = 0.0_8
            DO j = 3, 1, -1
                costb = costb + rc(j) * gradvb(j)
                rcb(j) = rcb(j) + cost * gradvb(j)
                gradvb(j) = 0.0_8
            END DO
            gradb = costb / r
            temp33b3 = 0.5d0 * grad2b
            aux3b = -(vj(2) * temp33b3)
            aux2b = 0.25d0 * gradb + aux * aux3b + temp33b3 / r
            auxb = 2 * aux * aux2b + aux2 * aux3b
            temp33b4 = -(auxb / (vj(2) * r + 1.d0)**2)
            rb = vj(2) * temp33b4 - aux2 * temp33b3 / r**2 - grad * costb / r**2
            vjb(2) = vjb(2) + r * temp33b4 - aux3 * temp33b3
        ELSE
            aux = 1.d0 / (1.d0 + vj(1) * r)
            aux2 = aux * aux
            aux3 = aux2 * aux
            grad = 0.5d0 * aux2
            cost = grad / r
            costb = 0.0_8
            DO j = 3, 1, -1
                costb = costb + rc(j) * gradvb(j)
                rcb(j) = rcb(j) + cost * gradvb(j)
                gradvb(j) = 0.0_8
            END DO
            gradb = costb / r
            aux3b = -(vj(1) * grad2b)
            aux2b = 0.5d0 * gradb + aux * aux3b + grad2b / r
            auxb = 2 * aux * aux2b + aux2 * aux3b
            temp33b2 = -(auxb / (vj(1) * r + 1.d0)**2)
            rb = vj(1) * temp33b2 - aux2 * grad2b / r**2 - grad * costb / r**2
            vjb(1) = vjb(1) + r * temp33b2 - aux3 * grad2b
        END IF
        !   CALL POPINTEGER4(branch)
        IF (x9 .GE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x9b = rb
        ELSE
            x9b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp33b1 = 0.0
        ELSE
            !     temp33b1 = x9b/(2.D0*DSQRT(rc(1)**2+rc(2)**2+rc(3)**2))
            temp33b1 = x9b / (2.D0 * r)
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp33b1
        rcb(2) = rcb(2) + 2 * rc(2) * temp33b1
        rcb(3) = rcb(3) + 2 * rc(3) * temp33b1
    CASE (-1)
        x10 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x10 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x10
            !     CALL PUSHINTEGER4(0)
        END IF
        !        cusp condition for parallel electrons
        aux = 1.d0 / (1.d0 + vj(1) * r)
        aux2 = aux * aux
        aux3 = aux2 * aux
        IF (ispin .GT. 0) THEN
            grad = 0.25d0 * aux2
            !        grad2=-vj(1)*(aux+aux2+aux3)
            cost = grad / r
            costb = 0.0_8
            DO j = 3, 1, -1
                costb = costb + rc(j) * gradvb(j)
                rcb(j) = rcb(j) + cost * gradvb(j)
                gradvb(j) = 0.0_8
            END DO
            gradb = costb / r
            temp33b7 = 0.5d0 * grad2b
            rb = -(aux2 * temp33b7 / r**2) - grad * costb / r**2
            aux2b = 0.25d0 * gradb + temp33b7 / r
            vjb(1) = vjb(1) - aux3 * temp33b7
            aux3b = -(vj(1) * temp33b7)
        ELSE
            grad = 0.5d0 * aux2
            !        grad2=-vj(1)*(aux+aux2+aux3)
            cost = grad / r
            costb = 0.0_8
            DO j = 3, 1, -1
                costb = costb + rc(j) * gradvb(j)
                rcb(j) = rcb(j) + cost * gradvb(j)
                gradvb(j) = 0.0_8
            END DO
            gradb = costb / r
            rb = -(aux2 * grad2b / r**2) - grad * costb / r**2
            aux2b = 0.5d0 * gradb + grad2b / r
            vjb(1) = vjb(1) - aux3 * grad2b
            aux3b = -(vj(1) * grad2b)
        END IF
        aux2b = aux2b + aux * aux3b
        auxb = 2 * aux * aux2b + aux2 * aux3b
        temp33b6 = -(auxb / (vj(1) * r + 1.d0)**2)
        vjb(1) = vjb(1) + r * temp33b6
        rb = rb + vj(1) * temp33b6
        !   CALL POPINTEGER4(branch)
        IF (x10 .GE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x10b = rb
            !     temp33b5 = x10b/(2.D0*DSQRT(rc(1)**2+rc(2)**2+rc(3)**2))
            temp33b5 = x10b / (2.D0 * r)
        ELSE
            x10b = 0.D0
            temp33b5 = 0.0
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp33b5
        rcb(2) = rcb(2) + 2 * rc(2) * temp33b5
        rcb(3) = rcb(3) + 2 * rc(3) * temp33b5
    CASE (-2)
        !           jastrow=dexp(jastrow)
        rz = DSQRT(vj(1)**2 * (rc(1)**2 + rc(2)**2) + (vj(2) * rc(3))**2)
        x11 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x11 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x11
            !     CALL PUSHINTEGER4(0)
        END IF
        !        jastrow=dexp(jastrow)
        aux = 0.5d0 / (1.d0 + rz)**2 / rz / r
        aux2 = vj(2)**2 - vj(1)**2
        acost = aux2 * rc(3)**2
        bcost = -(aux2 * (rc(1)**2 + rc(2)**2))
        !	 write(6,*) ' Grad =',j,gradv(j)
        !	 write(6,*) ' Grad =',3,gradv(3)
        ! ! the trivial laplacian term
        dxrz = -(aux / rz / (1.d0 + rz) * (acost + 3.d0 * acost * rz + 2.d0 * rz**2))
        dxr = -(aux / r * (acost + rz))
        dxrz_old = dxrz
        !   CALL PUSHREAL8(dxrz)
        dxrz = -(aux / rz / (1.d0 + rz) * (bcost + 3.d0 * bcost * rz + 2.d0 * rz**2))
        !   CALL PUSHREAL8(dxr)
        dxr_old = dxr
        dxr = -(aux / r * (bcost + rz))
        temp42 = dxrz / rz
        temp43b = rc(3)**2 * grad2b
        temp42b = vj(2)**2 * temp43b / rz
        rcb(3) = rcb(3) + (dxr / r + vj(2)**2 * temp42) * 2 * rc(3) * grad2b
        dxrb = temp43b / r
        rb = -(dxr * temp43b / r**2)
        vjb(2) = vjb(2) + temp42 * 2 * vj(2) * temp43b
        dxrzb = temp42b
        temp41 = aux / r
        rzb = -(temp41 * dxrb) - temp42 * temp42b
        !   CALL POPREAL8(dxr)
        dxr = dxr_old
        temp41b = -((bcost + rz) * dxrb / r)
        temp39 = rz * (rz + 1.d0)
        temp40 = aux / temp39
        temp41b0 = -(temp40 * dxrzb)
        temp35b0 = aux * grad2b
        temp35b1 = rc(3) * aux * gradvb(3)
        bcostb = (3.d0 * rz + 1.0_8) * temp41b0 + temp35b1 + temp35b0 - temp41 * &
                &      dxrb
        temp40b = -((bcost + 3.d0 * (bcost * rz) + 2.d0 * rz**2) * dxrzb / temp39)
        temp39b = (rc(1)**2 + rc(2)**2) * grad2b
        temp38b = vj(1)**2 * temp39b / rz
        dxrb = temp39b / r
        dxrzb = temp38b
        temp37b = -((acost + rz) * dxrb / r)
        temp35 = rz * (rz + 1.d0)
        temp36b = -((acost + 3.d0 * (acost * rz) + 2.d0 * rz**2) * dxrzb / temp35)
        auxb = temp40b + temp36b + (bcost + rz) * rc(3) * gradvb(3) + (2.d0 * acost + &
                &      bcost + 3.d0 * rz) * grad2b + temp37b + temp41b
        temp37 = aux / r
        rb = rb - dxr * temp39b / r**2 - temp37 * temp37b - temp41 * temp41b
        !   CALL POPREAL8(dxrz)
        dxrz = dxrz_old
        temp39b0 = -(temp40 * temp40b)
        temp38 = dxrz / rz
        temp36 = aux / temp35
        temp37b0 = -(temp36 * dxrzb)
        temp35b2 = -(temp36 * temp36b)
        rzb = rzb + (2.d0 * 2 * rz + 3.d0 * acost) * temp37b0 - temp38 * temp38b + (2 * rz&
                & + 1.d0) * temp35b2 + temp35b1 + 3.d0 * temp35b0 - temp37 * dxrb + (2 * rz + &
                &      1.d0) * temp39b0 + (2.d0 * 2 * rz + 3.d0 * bcost) * temp41b0
        temp39b1 = (dxr / r + vj(1)**2 * temp38) * grad2b
        rcb(1) = rcb(1) + 2 * rc(1) * temp39b1
        rcb(2) = rcb(2) + 2 * rc(2) * temp39b1
        vjb(1) = vjb(1) + temp38 * 2 * vj(1) * temp39b
        acostb = (3.d0 * rz + 1.0_8) * temp37b0 + 2.d0 * temp35b0 - temp37 * dxrb
        rcb(3) = rcb(3) + (bcost + rz) * aux * gradvb(3)
        gradvb(3) = 0.0_8
        DO j = 2, 1, -1
            temp35b = rc(j) * aux * gradvb(j)
            rcb(j) = rcb(j) + (acost + rz) * aux * gradvb(j)
            auxb = auxb + (acost + rz) * rc(j) * gradvb(j)
            acostb = acostb + temp35b
            rzb = rzb + temp35b
            gradvb(j) = 0.0_8
        END DO
        aux2b = rc(3)**2 * acostb - (rc(1)**2 + rc(2)**2) * bcostb
        rcb(1) = rcb(1) - aux2 * 2 * rc(1) * bcostb
        rcb(2) = rcb(2) - aux2 * 2 * rc(2) * bcostb
        rcb(3) = rcb(3) + aux2 * 2 * rc(3) * acostb
        vjb(2) = vjb(2) + 2 * vj(2) * aux2b
        vjb(1) = vjb(1) - 2 * vj(1) * aux2b
        temp34 = (rz + 1.d0)**2 * rz * r
        temp34b1 = -(0.5d0 * auxb / temp34**2)
        temp34b2 = (rz + 1.d0)**2 * temp34b1
        rzb = rzb + r * temp34b2 + rz * r * 2 * (rz + 1.d0) * temp34b1
        rb = rb + rz * temp34b2
        !   CALL POPINTEGER4(branch)
        IF (x11 .LT. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x11b = rb
        ELSE
            x11b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp34b = 0.0
        ELSE
            temp34b = x11b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp34b
        rcb(2) = rcb(2) + 2 * rc(2) * temp34b
        rcb(3) = rcb(3) + 2 * rc(3) * temp34b
        temp33 = rc(1)**2 + rc(2)**2
        IF (vj(1)**2 * temp33 + (vj(2) * rc(3))**2 .EQ. 0.0) THEN
            temp34b0 = 0.0
        ELSE
            temp34b0 = rzb / (2.D0 * DSQRT(vj(1)**2 * temp33 + (vj(2) * rc(3))**2))
        END IF
        temp33b8 = vj(1)**2 * temp34b0
        temp33b9 = 2 * vj(2) * rc(3) * temp34b0
        vjb(1) = vjb(1) + temp33 * 2 * vj(1) * temp34b0
        rcb(1) = rcb(1) + 2 * rc(1) * temp33b8
        rcb(2) = rcb(2) + 2 * rc(2) * temp33b8
        vjb(2) = vjb(2) + rc(3) * temp33b9
        rcb(3) = rcb(3) + vj(2) * temp33b9
    CASE (3)
        x12 = DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2)
        IF (x12 .LT. 1d-9) THEN
            r = 1d-9
            !     CALL PUSHINTEGER4(1)
        ELSE
            r = x12
            !     CALL PUSHINTEGER4(0)
        END IF
        aux = 1.d0 / (1.d0 + vj(1) * r)
        aux2 = aux * aux
        aux3 = aux2 * aux
        grad = 0.5d0 * aux2
        aux_old = aux
        !   CALL PUSHREAL8(aux)
        !        grad2=-vj(1)*(aux+aux2+aux3)
        aux = r / (1.d0 + vj(2) * r)**2
        aux2_old = aux2
        !   CALL PUSHREAL8(aux2)
        aux2 = aux / (1.d0 + vj(2) * r)
        !     jastrow=dexp(jastrow)
        grad = grad + vj(3) * aux2
        aux3 = aux3 + 3.d0 * vj(3) * aux / (1.d0 + vj(2) * r)**2
        cost = grad / r
        costb = 0.0_8
        DO j = 3, 1, -1
            costb = costb + rc(j) * gradvb(j)
            rcb(j) = rcb(j) + cost * gradvb(j)
            gradvb(j) = 0.0_8
        END DO
        gradb = costb / r
        aux3b = grad2b / r
        temp44 = vj(2) * r + 1.d0
        temp45b = 3.d0 * aux3b / temp44**2
        temp44b = -(vj(3) * aux * 2 * temp45b / temp44)
        aux2b = vj(3) * gradb
        temp44b0 = aux2b / (vj(2) * r + 1.d0)
        auxb = temp44b0 + vj(3) * temp45b
        temp44b1 = -(aux * temp44b0 / (vj(2) * r + 1.d0))
        temp43 = (vj(2) * r + 1.d0)**2
        temp43b1 = -(r * 2 * (vj(2) * r + 1.d0) * auxb / temp43**2)
        rb = vj(2) * temp44b1 - aux3 * grad2b / r**2 + vj(2) * temp43b1 + auxb / &
                &      temp43 + vj(2) * temp44b - grad * costb / r**2
        vjb(3) = vjb(3) + aux * temp45b
        vjb(2) = vjb(2) + r * temp44b
        vjb(3) = vjb(3) + aux2 * gradb
        !   CALL POPREAL8(aux2)
        aux2 = aux2_old
        vjb(2) = vjb(2) + r * temp43b1 + r * temp44b1
        !   CALL POPREAL8(aux)
        aux = aux_old
        aux2b = aux * aux3b + 0.5d0 * gradb
        auxb = 2 * aux * aux2b + aux2 * aux3b
        temp43b2 = -(auxb / (vj(1) * r + 1.d0)**2)
        vjb(1) = vjb(1) + r * temp43b2
        rb = rb + vj(1) * temp43b2
        !   CALL POPINTEGER4(branch)
        IF (x12 .GE. 1d-9) THEN
            !   IF (branch .LT. 1) THEN
            x12b = rb
        ELSE
            x12b = 0.D0
        END IF
        IF (rc(1)**2 + rc(2)**2 + rc(3)**2 .EQ. 0.0) THEN
            temp43b0 = 0.0
        ELSE
            temp43b0 = x12b / (2.D0 * DSQRT(rc(1)**2 + rc(2)**2 + rc(3)**2))
        END IF
        rcb(1) = rcb(1) + 2 * rc(1) * temp43b0
        rcb(2) = rcb(2) + 2 * rc(2) * temp43b0
        rcb(3) = rcb(3) + 2 * rc(3) * temp43b0
    CASE (0)
        gradvb = 0.d0
    CASE DEFAULT
        STOP
    END SELECT
    grad2b = 0.0_8
END SUBROUTINE JASTROWGRAD_B
