!TL off
!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.3 (r3163) - 09/25/2009 09:03
!
!  Differentiation of jastrow_ei in reverse (adjoint) mode:
!   gradient, with respect to input variables: r vj
!   of linear combination of output variables: r vj jastrow_ei
SUBROUTINE JASTROW_EI_B(r, rb, vj, vjb, iesd, jastrow_eib)
    IMPLICIT NONE
    REAL*8 :: r, rz, jastrow_ei, vj(*)
    REAL*8 :: rb, jastrow_eib, vjb(*)
    INTEGER :: iesd
    INTRINSIC DEXP
    REAL*8 :: tempb2
    REAL*8 :: tempb1
    REAL*8 :: tempb0
    REAL*8 :: tempb

    SELECT CASE  (iesd)
    CASE (4)
        tempb = 0.5d0 * jastrow_eib / vj(1)
        tempb0 = -(DEXP(-(vj(1) * r)) * tempb)
        vjb(1) = vjb(1) - (1.d0 - DEXP(-(vj(1) * r))) * tempb / vj(1) - r * tempb0
        rb = rb - vj(1) * tempb0
    CASE (1)
        tempb1 = 0.5d0 * jastrow_eib / (vj(1) * r + 1.d0)
        tempb2 = -(r * tempb1 / (vj(1) * r + 1.d0))
        rb = rb + vj(1) * tempb2 + tempb1
        vjb(1) = vjb(1) + r * tempb2
    CASE(8)
        tempb0 = DEXP(-(vj(1) * r**3))

        rb = rb + jastrow_eib * 3 * r**2 * tempb0

        vjb(1) = vjb(1) + jastrow_eib * (tempb0 * (1.d0 + vj(1) * r**3) - 1.d0) / vj(1)**2

    END SELECT
    jastrow_eib = 0.d0
END SUBROUTINE JASTROW_EI_B
