!TL off
!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.2 (r3024) - 06/17/2009 13:03
!  
!  Differentiation of legfun in reverse (adjoint) mode:
!   gradient, with respect to input variables: cosa
!   of linear combination of output variables: cosa legfun
SUBROUTINE LEGFUN_B(i, cosa, cosab, legfunb)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8 :: cosa, legfun
    REAL*8 :: cosab, legfunb
    REAL*8 :: tempb0
    REAL*8 :: tempb
    !
    SELECT CASE  (i)

    CASE(0)
        ! do nothing

    CASE (1)
        cosab = cosab + legfunb
    CASE (2)
        cosab = cosab + 0.5 * 3.d0 * 2 * cosa * legfunb
    CASE (3)
        cosab = cosab + (0.5 * 5.d0 * 3 * cosa**2 - 0.5 * 3.d0) * legfunb
    CASE (4)
        cosab = cosab + (35.d0 * 4 * cosa**3 / 8.d0 - 30.d0 * 2 * cosa / 8.d0) * legfunb
    CASE (5)
        tempb = legfunb / 8.d0
        cosab = cosab + (63.d0 * 5 * cosa**4 - 70.d0 * 3 * cosa**2 + 15.d0) * tempb
    CASE (6)
        tempb0 = legfunb / 16.d0
        cosab = cosab + (105.d0 * 2 * cosa - 315.d0 * 4 * cosa**3 + 231.d0 * 6 * cosa**5) * &
                &      tempb0
    CASE DEFAULT
        write(6, *) 'WARNING: Legendre polynomial non defined for l', i
        stop
    END SELECT
END SUBROUTINE LEGFUN_B
