!TL off
!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.2 (r3024) - 06/17/2009 13:03
!  
!  Differentiation of subener in reverse (adjoint) mode:
!   gradient, with respect to input variables: winvup tabpip winvdo
!   of linear combination of output variables: winvup enercont
!                tabpip winvdo
SUBROUTINE SUBENER_B(indt, nelup, neldo, winvup, winvupb, winvdo, &
        &  winvdob, tabpip, tabpipb, enercont, enercontb)
    use constants, only : ipc
    IMPLICIT NONE
    INTEGER :: i, j, jj, indt, nelup, neldo, indel
    REAL*8 :: winvup(ipc * nelup, *), winvdo(ipc * neldo, *), tabpip(nelup + neldo, *), &
            &  enercont
    REAL*8 :: winvupb(ipc * nelup, *), winvdob(ipc * neldo, *), tabpipb(nelup + neldo, *&
            &), enercontb(ipc)

    if(ipc.eq.1) then

        DO j = 3, 1, -1
            DO i = neldo, 1, -1
                jj = indt + j
                tabpipb(i + nelup, jj) = tabpipb(i + nelup, jj) + (-2 * tabpip(i + nelup&
                        &, jj) - 2.d0 * winvdo(i, jj)) * enercontb(1)
                winvdob(i, jj) = winvdob(i, jj) - 2.d0 * tabpip(i + nelup, jj) * &
                        &        enercontb(1)
            END DO
        END DO
        DO i = neldo, 1, -1
            winvdob(i, indt + 4) = winvdob(i, indt + 4) - enercontb(1)
            tabpipb(i + nelup, indt + 4) = tabpipb(i + nelup, indt + 4) - enercontb(1)
        END DO
        DO j = 3, 1, -1
            DO i = nelup, 1, -1
                jj = indt + j
                tabpipb(i, jj) = tabpipb(i, jj) + ((-2) * tabpip(i, jj) - 2.d0 * winvup(&
                        &        i, jj)) * enercontb(1)
                winvupb(i, jj) = winvupb(i, jj) - 2.d0 * tabpip(i, jj) * enercontb(1)
            END DO
        END DO
        DO i = nelup, 1, -1
            winvupb(i, indt + 4) = winvupb(i, indt + 4) - enercontb(1)
            tabpipb(i, indt + 4) = tabpipb(i, indt + 4) - enercontb(1)
        END DO

    else

        DO j = 3, 1, -1
            DO i = neldo, 1, -1
                indel = 2 * i - 1
                jj = indt + j
                tabpipb(i + nelup, jj) = tabpipb(i + nelup, jj) + (-2 * tabpip(i + nelup&
                        &, jj) - 2.d0 * winvdo(indel, jj)) * enercontb(1) - 2.d0 * winvdo(indel + 1, jj) * enercontb(2)
                winvdob(indel, jj) = winvdob(indel, jj) - 2.d0 * tabpip(i + nelup, jj) * &
                        &        enercontb(1)
                winvdob(indel + 1, jj) = winvdob(indel + 1, jj) - 2.d0 * tabpip(i + nelup, jj) * &
                        &        enercontb(2)
            END DO
        END DO
        DO i = neldo, 1, -1
            indel = 2 * (i - 1) + 1
            winvdob(indel, indt + 4) = winvdob(indel, indt + 4) - enercontb(1)
            winvdob(indel + 1, indt + 4) = winvdob(indel + 1, indt + 4) - enercontb(2)
            tabpipb(i + nelup, indt + 4) = tabpipb(i + nelup, indt + 4) - enercontb(1)
        END DO
        DO j = 3, 1, -1
            DO i = nelup, 1, -1
                indel = 2 * i - 1
                jj = indt + j
                tabpipb(i, jj) = tabpipb(i, jj) + (-2 * tabpip(i, jj) - 2 * winvup(&
                        &        indel, jj)) * enercontb(1) - 2 * winvup(indel + 1, jj) * enercontb(2)
                winvupb(indel, jj) = winvupb(indel, jj) - 2.d0 * tabpip(i, jj) * enercontb(1)
                winvupb(indel + 1, jj) = winvupb(indel + 1, jj) - 2.d0 * tabpip(i, jj) * enercontb(2)
            END DO
        END DO
        DO i = nelup, 1, -1
            indel = 2 * i - 1
            winvupb(indel, indt + 4) = winvupb(indel, indt + 4) - enercontb(1)
            tabpipb(i, indt + 4) = tabpipb(i, indt + 4) - enercontb(1)
            winvupb(indel + 1, indt + 4) = winvupb(indel + 1, indt + 4) - enercontb(2)
        END DO
    endif
    enercontb = 0.d0
END SUBROUTINE SUBENER_B

