# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import subprocess
import glob
import re
import shutil

print(sys.base_prefix)

sys.path.insert(0, os.path.abspath('.'))
"""
source_root=os.path.abspath('.')
bin_path=os.path.dirname(subprocess.check_output(['which', 'turbo-genius.sh']).decode('utf-8'))
turbo_root=os.path.abspath(os.path.join(bin_path, '../'))
turbo_doc=os.path.abspath(os.path.join(turbo_root, 'doc'))
turbo_genius_root=os.path.abspath(os.path.join(turbo_root, 'turbo_genius_dist'))
turbo_genius_modules=os.path.abspath(os.path.join(turbo_root, 'turbo_genius_dist/turbo_genius'))
sys.path.insert(0, turbo_genius_root)
sys.path.insert(0, turbo_genius_modules)
"""

import sphinx_rtd_theme
import datetime

# -- Project information -----------------------------------------------------

project = 'TurboRVB userguides'
copyright = 'Kosuke Nakano (NIMS) and collaborators.'
author = 'Kosuke Nakano'

# The short X.Y version
today_date=datetime.datetime.today().strftime("%d/%m/%Y")
version = 'Updated on {}'.format(today_date)
# The full version, including alpha/beta/rc tags
release = 'Updated on {}'.format(today_date)


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
'sphinx.ext.todo',
'sphinx.ext.autodoc',
'sphinx.ext.napoleon',
'sphinx.ext.viewcode',
'sphinxcontrib_roles',
'sphinx.ext.imgmath'
]

imgmath_latex_preamble = r'''
\usepackage{braket}
'''

# configuration case.1: define roles as list (define only roles)
#roles = ['strike', 'red', 'blue']

# configuration case.2: define roles as dict (define roles and its style on HTML)
roles = {'strike': "text-decoration: line-through;",'red': "color: red;",'blue': "color: blue;"}

# To do
todo_include_todos = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ['.rst', '.README']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['**/99rubbish', '**/99archived']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# sphinx.ext.jsmath
extensions += ['sphinx.ext.imgmath']
imgmath_image_format='svg'
#extensions += ['sphinx.ext.jsmath']

# jsMath path
#jsmath_path = 'jsMath-3.6e/easy/load.js'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'bootstrap'
#html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
#html_theme_options = {'bootswatch_theme': "flatly"}

html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_style = "css/my_theme.css"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'TurboRVB_userguidesdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    'preamble': ['\\usepackage{braket}']
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'TurboRVB_userguides.tex', 'TurboRVB\\_userguides Documentation',
     'kosuke.nakano', 'userguides'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'turborvb_userguides', 'TurboRVB_userguides Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'TurboRVB_userguides', 'TurboRVB_userguides Documentation',
     author, 'TurboRVB_userguides', 'One line description of project.',
     'Miscellaneous'),
]


# -- Readme Integration-----------------------------------------------------
"""
readme_doc_list = [os.path.split(f)[1] for f in glob.glob(turbo_doc+'/*.README')]
readme_exist_list = [os.path.split(f)[1] for f in glob.glob(source_root+'/_sources/00users_manual/01turborvb/98readmes/*.README')]
copy_readme_list = set(readme_doc_list) & set(readme_exist_list)
print("=====Copy Readme======")

for copy_readme in copy_readme_list:
    print(" Copy " + copy_readme)
    shutil.copyfile(turbo_doc+"/"+copy_readme, source_root+"/_sources/00users_manual/01turborvb/98readmes/"+copy_readme)

for i in range(65, 91):
    alphabet=chr(i)
    l_start = [s for s in copy_readme_list if s.startswith(alphabet.upper()) or s.startswith(alphabet.lower())]
    if len(l_start) > 0:
        print(f"^^^")
        print(alphabet.upper())
        print(f"^^^")

        print("")
        print(".. toctree::")
        print("   :maxdepth: 1")
        print("")
        
        for l_ in l_start:
            print("   ./98readmes/"+l_)
        
        print("")

sys.exit()
"""
