/* include/c_defs.h.  Generated by configure.  */
/*
! Copyright (C) 2022 TurboRVB group based on code by
! Copyright (C) 2006 QUANTUM-ESPRESSO group
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program. If not, see <http://www.gnu.org/licenses/>.
!
*/

/* File c_defs.h.in is used by configure to generate c_defs.h
   Variables that configure defines should be #undef-ined in
   include/c_defs.h.in !!! */

/* fortran-to-C naming convention, for functions with and without
   underscores in the name (some compilers treat them differently) */

#ifdef RISC
#define F77_FUNC_(name, NAME) name
#else
#define F77_FUNC_(name, NAME) name##_
#endif

/* do we have the mallinfo structure (see clib/memstat.c) ? */

#define HAVE_MALLINFO 1
